# Generated by Django 2.2.7 on 2020-01-25 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puser',
            name='d_id',
        ),
        migrations.AddField(
            model_name='donor',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.PUser'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_requests',
            name='r_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
