# Generated by Django 2.2.7 on 2020-01-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200125_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_records',
            name='d_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Donor'),
        ),
    ]
