# Generated by Django 2.2.7 on 2020-01-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200126_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_records',
            name='b_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_records',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_records',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
