# Generated by Django 2.2.7 on 2020-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200219_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
