# Generated by Django 2.2.7 on 2020-02-19 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200219_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='puser',
            name='contact',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='puser',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name cannot include numbers', regex='^[a-zA-Z ]+$')]),
        ),
    ]
